### ISSUE TITLE
No notifications of new pages

### ISSUE THREAD

**Issue by EvHaus** [grundleborg/mediawiki-slack#1]
Page modifications seem to be working well, but when new pages are added to the wiki, no notification is sent to Slack. Is there an option we can configure somewhere to turn that on?

**Comment by grundleborg** [comment]
You are quite right that this script currently doesn't do anything on new pages being created. I've been meaning to do that for a while, but haven't got round to it yet. I'm happy to take a patch, or I might eventually get it done myself!

**Comment by grundleborg** [comment]
Fixed by MR #11

**Comment by EvHaus** [comment]
Thanks, it works now!
