### ISSUE TITLE
Worked beautifully, then stopped

### ISSUE THREAD

**Issue by dfriedla** [grundleborg/mediawiki-slack#15]
Has anyone else had this suddenly stop working for no discernible reason? My installation last pushed a notification through to Slack on September 16. (I don't think we changed anything on the wiki site around that time, either.) We absolutely LOVED this integration, and I want to get it back online!

I tried generating a new webhook and updating that info in localsettings.php, but it remains stubbornly quiet in that channel. What else should I try to troubleshoot this?

**Comment by benhutchins** [comment]
@dfriedla I haven't seen any issues, what version of MediaWiki are you running, and your `LocalSettings.php` still has the inclusion for `Slack.php`?

**Comment by dfriedla** [comment]
@benhutchins Thanks for the speedy response!!

We're running MediaWiki 1.25.1. I just confirmed that LocalSettings.php includes "require_once "$IP/extensions/Slack/Slack.php";" as well as the configuration options.

**Comment by benhutchins** [comment]
@dfriedla I'm not seeing any issues with my current installation using the latest mediawiki-slack `1.0.1`.  Can you verify these things:
- That the configured `$wgSlackChannel` still exists on Slack.
- That the configured Slack API endpoint is configured properly on Slack's service (you can test it using a simple curl request, see https://api.slack.com/incoming-webhooks "Putting it all together")
- Try that same curl request on the server running your mediawiki instance (will rule out an outgoing firewall restriction)
- Confirm your PHP is configured to allow `file_get_contents` to be used for web requests, which is what `mediawiki-slack` [uses](https://github.com/grundleborg/mediawiki-slack/blob/master/Slack.hooks.php#L58). I believe `allow_url_fopen` can restrict this, read more [here](http://php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen)

Still not working, then enable MediaWiki [debug logging](https://www.mediawiki.org/wiki/Manual:How_to_debug#Setting_up_a_debug_log_file) and look at the file after saving a page. You should see `Slack Result: ......` - which may contain an error message or just `false` if the request failed.

Hopefully something here helps you resolve it.

**Comment by dfriedla** [comment]
Doh! File this one under PEBCAK, ID10T error, whatever you want to call it: I had changed the name of the channel in Slack but not in LocalSettings.php.

So it actually was working just as it should; the messages were just going to a channel that doesn't exist anymore.

Thank you so much for your help, @benhutchins!! That first bullet in your reply is what led me straight to the problem.
