### ISSUE TITLE
Please remove wikimedia and mediawiki from Packagist maintainers

### ISSUE THREAD

**Issue by bd808** [grundleborg/mediawiki-slack#5]
Thanks for working on cool things to add to MediaWiki!

I'd appreciate it however if you didn't imply official affiliation of this extension with the Wikimedia Foundation and the MediaWiki project by adding our Packagist accounts as co-maintainers. It's perfectly acceptable to use "mediawiki" as your namespace identifier to increase SEO for your extension.

**Comment by legoktm** [comment]
Alternatively, would you be willing to move your repository to Wikimedia's gerrit installation? It would increase the discoverability of your extension and other MediaWiki developers would better be able to give code review and tips.

See https://www.mediawiki.org/wiki/Gerrit/New_repositories for details on how to get access.

**Comment by grundleborg** [comment]
Apologies. I got the idea that it was bad form _not_ to include those as maintainers when using the mediawiki namespace - a misunderstanding of the extension writing docs.

I might try to move it to gerrit when I have more time, but it's a bit too much hassle for the moment.
